### ISSUE TITLE
Support editing of vis title and description

### ISSUE THREAD

**Issue by ronichoudhury** [XDATA-Year-2/sitar#20]

**Comment by ronichoudhury** [comment]
Look into using Fuel UX placards for this.

**Comment by jeffbaumes** [comment]
Fuel UX looks pretty good - and doesn't seem to add too much on top of Bootstrap.

**Comment by ronichoudhury** [comment]
I am using the Fuel UX Wizard right now to redo the "new vis" view.  It's pretty neat, come and take a look if you like.
