### ISSUE TITLE
If there is no "sitar" collection, either create it or tell the user to create it

### ISSUE THREAD

**Issue by ronichoudhury** [XDATA-Year-2/sitar#5]
The latter option is probably safer, and definitely easier.

**Comment by jeffbaumes** [comment]
On creation of first vis, create sitar folder

**Comment by ronichoudhury** [comment]
Insert code in the User readHandler's deferred pipeline, just after the "sitar" folder is searched for - if it does not exist, insert additional/alternative pipeline stages to create it and the visualization/data folders.
